---
name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"

      - uses: actions/cache@v2
        with:
          path: |
            venv
          key: ${{ runner.os }}-venv-v2-${{ hashFiles('**/*requirements.txt') }}

      - name: Install dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip pip-tools
          pip-sync requirements.txt dev-requirements.txt

      - name: Run the linter
        run: |
          . venv/bin/activate
          make lint

  build-docker-image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate image identifier
        id: image
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to the custom container registry
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_HOST }}
          username: ${{ secrets.CONTAINER_REGISTRY_LOGIN }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build the image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: |
            ghcr.io/${{ steps.image.outputs.lowercase }}:latest
            ghcr.io/${{ steps.image.outputs.lowercase }}:${{ github.sha }}
            ${{ secrets.CONTAINER_REGISTRY_HOST }}/${{ steps.image.outputs.lowercase }}:latest
            ${{ secrets.CONTAINER_REGISTRY_HOST }}/${{ steps.image.outputs.lowercase }}:${{ github.sha }}
